name: wifi_hunter
description: A flutter package to hunt down info from all WiFi APs around you.
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: klydra.wifi_hunter
        pluginClass: WiFiHunterPlugin