name: wifi_hunter
description: A flutter package to hunt down info from all WiFi APs around you.
version: 1.1.0+1
homepage: https://github.com/klydra/wifi_hunter
repository: https://github.com/klydra/wifi_hunter.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: klydra.wifi_hunter
        pluginClass: WiFiHunterPlugin